app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Invoice;
use App\Item;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;


Route::get('/login', function () {
    return view('auth.login');
});

Route::get('/', function () {
    return view('welcome');
});


Route::auth();



Route::group(['middleware' => 'admin'] , function (){
    Route::any('/searchcustomer',function(){
        $customer_search = Input::get ( 'customer_search' );
        $customers = \App\Customer::where('buyer_name','LIKE','%'.$customer_search.'%')->orWhere('buyer_surname','LIKE','%'.$customer_search.'%')->paginate(12);

        if(count($customers) > 0)
            return view('admin.Customers.index' , compact('customers'));
        else return view ('admin.Customers.index' , compact('customers'));
    });

    Route::any('/searchitem',function(){
        $item_search = Input::get ( 'item_search' );
        $items = Item::where('name','LIKE','%'.$item_search.'%')->paginate(12);

        if(count($items) > 0)
            return view('admin.Items.index' , compact('items'));
        else return view ('admin.Items.index' , compact('items'));
    });

//    Route::any('/searchinvoice',function(){
//        $invoice_search = Input::get ( 'invoice_search' );
//
//        if($invoice_search == ""){
//            $invoices = Invoice::with('items')->orderBy('id' , 'desc')->paginate(10);
//            return view('admin.Invoices.index' , compact('invoices'));
//        }
//
//        $customers = \App\Customer::withTrashed()->where('buyer_name','LIKE','%'.$invoice_search.'%')->orWhere('buyer_surname','LIKE','%'.$invoice_search.'%')->paginate(12);
//        $invoice_tot = [];
//        $cnt = 0;
//        foreach ($customers as $customer){
//
//           $invoices = Invoice::where('customer_id','LIKE','%'.$customer->id.'%')->paginate(12);
//
//
//           foreach ($invoices as $invoice){
//               $invoice_tot[$cnt]= $invoice ;
//               $cnt++;
//           }
//        }
//
//    $invoices2 = (object)$invoice_tot;
//
//
//         if(!isset($invoices2)){
//             $invoices2 = Invoice::where('id' , '=' , '1.1')->paginate(10);
//             return view('admin.Invoices.index' , compact('invoices2'));
//
//         }
//
//        if(count($invoices2) > 0)
//            return view('admin.Invoices.index' , compact('invoices2'));
//        else return view ('admin.Invoices.index' , compact('invoices2'));
//    });

    Route::get('/admin/customers/{id}/invoices', [
        'uses' => 'AdminCustomersController@invoiceFilter',
        'as' => 'admin.customers.invoices'
    ]);
    Route::resource('/admin/items' , 'AdminItemsController');
    Route::resource('admin/customers' , 'AdminCustomersController');
    Route::resource('admin/invoices' , 'AdminInvoicesController');
    Route::resource('admin/purchase/invoices/','AdminPurchaseInvoicesController');


});

Route::get('/test', function (){


//        $invoice = Invoice::onlyTrashed()->restore();


    $invoices = Invoice::with('customer')->get();

    foreach ($invoices as $invoice){
        dd($invoice->customer->buyer_name);
    }



//
//    foreach ($invoices as $invoice){
//
//       // dd($invoice->items[0]->name);
//
//        foreach ($invoice->items as $item)
//        {
//            dd($item->pivot->quantity);
//        }
//
//    }

    //dd($invoices);

//    $client_total = DB::table('invoices')
//                ->select(DB::raw('sum(total_with_tax) as customer_total, customer_id '))
//                ->groupBy('customer_id')
//                ->get();
//
//    dd($client_total);

//    $invoice = Invoice::find(76);
////        dd($invoice->items);
//
//    foreach ($invoice->items as $item){
//
//        echo $item->name . " " . $item->pivot->quantity ;
//
//
//        DB::table('items')->where('id','=', $item->id)->update([
//            'quantity' => $item->quantity - $item->pivot->quantity
//        ]);
//
//    }
//
//
//    dd();
//    dd($invoice->items->quantity);


});

Route::get('/home', 'HomeController@index');


//Route::get('/admin/items' , 'AdminItemsController@index');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'id',
        'name',
        'unit',
        'unit_price',
        'quantity',
        'created_at',
        'updated_at'
    ];
    protected $dates = ['deleted_at'];
    public function invoices(){
        return $this->belongsToMany('App\Invoice')->withPivot(['quantity' , 'unit_price_without_tax' , 'total_without_tax' , 'tax' , 'total_with_tax' , 'created_at']);
    }
}

resources/views/admin/Items/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">
        <h1 class="page-header">Shto Produkt Te Ri</h1>

        <div class="col-sm-4">

            {!! Form::open(['method'=>'POST','action'=>'AdminItemsController@store' , 'files' => true , 'onsubmit' => 'return confirm("Je i sigurt qe do ta shtosh kete produkt ne magazine?")'])!!}

            {!! csrf_field() !!}

            <div class="form-group">
                {!! Form::label('name','Pershkrimi i mallit:') !!}
                {!! Form::text('name',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('unit','Njesia') !!}
                {!! Form::select('unit', ['kg' => 'kg', 'cop' => 'cop' , 'liter' => 'liter'], null, ['placeholder' => 'Kliko ketu per te zgjedhur njesine']); !!}
            </div>

            <div class="form-group">
                {!! Form::label('unit_price','Cmimi baze') !!}
                {!! Form::text('unit_price',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('quantity','Sasia') !!}
                {!! Form::number('quantity',null,['class'=>'form-control']) !!}
            </div>

            {{--<div class="form-group">--}}
            {{--{!! Form::file('file',['class'=>'form-control']) !!}--}}
            {{--</div>--}}

            <div class="form-group">

                {!! Form::submit('Kliko per te shtuar produktin' , ['class'=>'btn btn-info']) !!}
            </div>

            {!! Form::close() !!}

        </div>


    </div>


    @include('admin.includes.createFormError')

@endsection

resources/views/admin/Items/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">
        <h1 class="page-header">Ndrysho produktin</h1>

        <div class="col-sm-4">

            {!! Form::model($item , ['method'=>'PATCH','action'=>['AdminItemsController@update' , $item->id] , 'files' => true , 'onsubmit' => 'return confirm("Je i sigurt qe do ta ndryshosh kete produkt?")'])!!}

            {!! csrf_field() !!}

            <div class="form-group">
                {!! Form::label('name','Pershkrimi i mallit:') !!}
                {!! Form::text('name',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('unit','Njesia') !!}
                {!! Form::select('unit', ['kg' => 'kg', 'cop' => 'cop' , 'liter' => 'liter'], null, ['placeholder' => 'Zgjidh njesine']); !!}
            </div>

            <div class="form-group">
                {!! Form::label('unit_price','Cmimi baze') !!}
                {!! Form::number('unit_price',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('quantity','Sasia') !!}
                {!! Form::number('quantity',null,['class'=>'form-control']) !!}
            </div>

            {{--<div class="form-group">--}}
            {{--{!! Form::file('file',['class'=>'form-control']) !!}--}}
            {{--</div>--}}

            <div class="form-group">

                {!! Form::submit('Kliko per te ndryshuar produktin' , ['class'=>'btn btn-info']) !!}
            </div>

            {!! Form::close() !!}

        </div>


    </div>


    @include('admin.includes.createFormError')

@endsection

resources/views/admin/Items/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1 class="page-header text-center">Inventari</h1>

    <div class="container-fluid">
        <form action="/searchitem" method="POST" role="search" style="width: 310px; height: 70px">
            {{ csrf_field() }}
            <div class="input-group" >
                <input type="text" class="form-control" name="item_search"
                       placeholder="Kerko produktet sipas pershkrimit"> <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </form>
        <div class="table-responsive">
            <?php $nr = 1; ?>
            <table class="table table-hover ">
                <thead>
                <tr>

                    <th>Nr</th>
                    <th>Pershkrimi i mallit</th>
                    <th>Njesia</th>
                    <th>Cmimi baze</th>
                    <th>Sasia</th>
                    <th></th>

                </tr>
                </thead>
                <tbody>
                @if($items)

                    @foreach($items as $item)
                        <tr>

                            <td><?php echo $nr++ ?></td>
                            <td>{{$item->name}}</td>
                            <td>{{$item->unit}}</td>
                            <td>{{$item->unit_price}}</td>
                            <td>{{number_format($item->quantity)}}</td>
                            <td style="width: 50px"><a href="{{route('admin.items.edit' , $item->id)}}" class="btn btn-info" role="button">Ndrysho produktin</a></td>
                            {{--<td><button type="button" class="btn btn-primary"><a href="{{route('admin.items.edit' , $item->id)}}">Ndrysho</a></button></td>--}}
                        </tr>
                    @endforeach

                @endif

                </tbody>
            </table>
        </div>
        <div style="position: relative;">{{$items->render()}}</div>
    </div>

    @endsection