app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Invoice;
use App\Item;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;


Route::get('/login', function () {
    return view('auth.login');
});

Route::get('/', function () {
    return view('welcome');
});


Route::auth();



Route::group(['middleware' => 'admin'] , function (){
    Route::any('/searchcustomer',function(){
        $customer_search = Input::get ( 'customer_search' );
        $customers = \App\Customer::where('buyer_name','LIKE','%'.$customer_search.'%')->orWhere('buyer_surname','LIKE','%'.$customer_search.'%')->paginate(12);

        if(count($customers) > 0)
            return view('admin.Customers.index' , compact('customers'));
        else return view ('admin.Customers.index' , compact('customers'));
    });

    Route::any('/searchitem',function(){
        $item_search = Input::get ( 'item_search' );
        $items = Item::where('name','LIKE','%'.$item_search.'%')->paginate(12);

        if(count($items) > 0)
            return view('admin.Items.index' , compact('items'));
        else return view ('admin.Items.index' , compact('items'));
    });

//    Route::any('/searchinvoice',function(){
//        $invoice_search = Input::get ( 'invoice_search' );
//
//        if($invoice_search == ""){
//            $invoices = Invoice::with('items')->orderBy('id' , 'desc')->paginate(10);
//            return view('admin.Invoices.index' , compact('invoices'));
//        }
//
//        $customers = \App\Customer::withTrashed()->where('buyer_name','LIKE','%'.$invoice_search.'%')->orWhere('buyer_surname','LIKE','%'.$invoice_search.'%')->paginate(12);
//        $invoice_tot = [];
//        $cnt = 0;
//        foreach ($customers as $customer){
//
//           $invoices = Invoice::where('customer_id','LIKE','%'.$customer->id.'%')->paginate(12);
//
//
//           foreach ($invoices as $invoice){
//               $invoice_tot[$cnt]= $invoice ;
//               $cnt++;
//           }
//        }
//
//    $invoices2 = (object)$invoice_tot;
//
//
//         if(!isset($invoices2)){
//             $invoices2 = Invoice::where('id' , '=' , '1.1')->paginate(10);
//             return view('admin.Invoices.index' , compact('invoices2'));
//
//         }
//
//        if(count($invoices2) > 0)
//            return view('admin.Invoices.index' , compact('invoices2'));
//        else return view ('admin.Invoices.index' , compact('invoices2'));
//    });

    Route::get('/admin/customers/{id}/invoices', [
        'uses' => 'AdminCustomersController@invoiceFilter',
        'as' => 'admin.customers.invoices'
    ]);
    Route::resource('/admin/items' , 'AdminItemsController');
    Route::resource('admin/customers' , 'AdminCustomersController');
    Route::resource('admin/invoices' , 'AdminInvoicesController');
    Route::resource('admin/purchase/invoices/','AdminPurchaseInvoicesController');


});

Route::get('/test', function (){


//        $invoice = Invoice::onlyTrashed()->restore();


    $invoices = Invoice::with('customer')->get();

    foreach ($invoices as $invoice){
        dd($invoice->customer->buyer_name);
    }



//
//    foreach ($invoices as $invoice){
//
//       // dd($invoice->items[0]->name);
//
//        foreach ($invoice->items as $item)
//        {
//            dd($item->pivot->quantity);
//        }
//
//    }

    //dd($invoices);

//    $client_total = DB::table('invoices')
//                ->select(DB::raw('sum(total_with_tax) as customer_total, customer_id '))
//                ->groupBy('customer_id')
//                ->get();
//
//    dd($client_total);

//    $invoice = Invoice::find(76);
////        dd($invoice->items);
//
//    foreach ($invoice->items as $item){
//
//        echo $item->name . " " . $item->pivot->quantity ;
//
//
//        DB::table('items')->where('id','=', $item->id)->update([
//            'quantity' => $item->quantity - $item->pivot->quantity
//        ]);
//
//    }
//
//
//    dd();
//    dd($invoice->items->quantity);


});

Route::get('/home', 'HomeController@index');


//Route::get('/admin/items' , 'AdminItemsController@index');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Customer extends Model
{
    //

    use SoftDeletes;

    protected $fillable = [
        'id',
        'buyer_name',
        'buyer_surname',
        'buyer_phone_number',
        'nipt',
        'address',
        'transporter_name',
        'transporter_surname',
        'transporter_phone_number',
        'created_at',
        'updated_at'
    ];

    protected $dates = ['deleted_at'];

    public function invoices(){
        return $this->hasMany('App\Invoice');
    }
}

resources/views/admin/Customers/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">
        <h1 class="page-header">Shto Klient Te Ri </h1>

        <div class="col-sm-4">

            {!! Form::open(['method'=>'POST','action'=>'AdminCustomersController@store' , 'files' => true , 'onsubmit' => 'return confirm("Je i sigurt qe do ta krijosh kete klient?")'])!!}

            {!! csrf_field() !!}

            <div class="form-group">
                {!! Form::label('buyer_name','Emri') !!}
                {!! Form::text('buyer_name',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('buyer_surname','Mbiemri') !!}
                {!! Form::text('buyer_surname',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('buyer_phone_number','Numer Celulari') !!}
                {!! Form::text('buyer_phone_number',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('address','Adresa') !!}
                {!! Form::text('address',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('nipt','NIPT') !!}
                {!! Form::text('nipt',null,['class'=>'form-control']) !!}
            </div>



            {{--<div class="form-group">--}}
            {{--{!! Form::file('file',['class'=>'form-control']) !!}--}}
            {{--</div>--}}

            <div class="form-group">

                {!! Form::submit('Kliko per te shtuar klientin' , ['class'=>'btn btn-info']) !!}
            </div>

            {!! Form::close() !!}

        </div>


    </div>


    @include('admin.includes.createFormError')

@endsection

resources/views/admin/Customers/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">
        <h1 class="page-header">Ndrysho Te Dhenat E Klientit </h1>

        <div class="col-sm-4">

            {!! Form::model($customer , ['method'=>'PATCH','action'=>['AdminCustomersController@update' , $customer->id], 'files' => true , 'onsubmit' => 'return confirm("Je i sigurt qe do ta ndryshosh klientin?")'])!!}

            {!! csrf_field() !!}

            <div class="form-group">
                {!! Form::label('buyer_name','Emri') !!}
                {!! Form::text('buyer_name',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('buyer_surname','Mbiemri') !!}
                {!! Form::text('buyer_surname',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('buyer_phone_number','Numer Celulari') !!}
                {!! Form::text('buyer_phone_number',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('address','Adresa') !!}
                {!! Form::text('address',null,['class'=>'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('nipt','NIPT') !!}
                {!! Form::text('nipt',null,['class'=>'form-control']) !!}
            </div>



            {{--<div class="form-group">--}}
            {{--{!! Form::file('file',['class'=>'form-control']) !!}--}}
            {{--</div>--}}

            <div class="form-group">

                {!! Form::submit('Kliko per te ndryshuar klientin' , ['class'=>'btn btn-info']) !!}
            </div>

            {!! Form::close() !!}

            {!! Form::open(['method' => 'DELETE' , 'action' => ['AdminCustomersController@destroy', $customer->id] , 'onsubmit' => 'return confirm("Je i sigurt qe do ta fshish kete klient??")'])!!}
            <div class="form-group">

                {!! Form::submit('FSHI' , ['class'=>'btn btn-danger']) !!}
            </div>
            {!! Form::close() !!}


        </div>


    </div>


    @include('admin.includes.createFormError')

@endsection

resources/views/admin/Customers/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">


        <h1 class="page-header text-center">Klientet</h1>
        <form action="/searchcustomer" method="POST" role="search" style="width: 310px; height: 70px">
            {{ csrf_field() }}
            <div class="input-group" >
                <input type="text" class="form-control" name="customer_search"
                       placeholder="Kerko klientet sipas emrit ose mbiemrit"> <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </form>
        <div class="table-responsive">
            <table class="table table-hover table-condensed ">
                <thead>
                <tr>

                    <th>Nr</th>
                    <th>Emri</th>
                    <th>Mbiemri</th>
                    <th>Numer celulari</th>
                    <th>Adresa</th>
                    <th>NIPT</th>
                    <th></th>
                    <th></th>

                </tr>
                </thead>
                <tbody>

                @if($customers)

                    @foreach($customers as $customer)
                        <tr>
                            <td>{{$nr++}}</td>
                            <td>{{$customer->buyer_name}}</td>
                            <td>{{$customer->buyer_surname}}</td>
                            <td>{{$customer->buyer_phone_number}}</td>
                            <td>{{$customer->address}}</td>
                            <td>{{$customer->nipt}}</td>
                            <td style="width: 50px"><a href="{{route('admin.customers.invoices' , $customer->id)}}" class="btn btn-info" role="button">Shiko Faturat E Klientit</a></td>
                            <td style="width: 50px"><a href="{{route('admin.customers.edit' , $customer->id)}}" class="btn btn-info" role="button">Ndrysho Te Dhenat E Klientit</a></td>
                        </tr>
                    @endforeach

                @endif

                </tbody>
            </table>
            <div style="position: relative;">{{$customers->render()}}</div>
        </div>
    </div>

@endsection